/** 온체인 거래 카드와 그 칸들이 같이 쓰는 스타일 */
export const styles = {
  list: { display: 'flex', flexDirection: 'column' as const, gap: 14 },
  card: { border: '1px solid #E5E7EB', borderRadius: 10, padding: 14, display: 'flex', flexDirection: 'column' as const, gap: 12 },
  head: { display: 'flex', alignItems: 'center', gap: 8 },
  clickable: { cursor: 'pointer' },
  chevron: { color: '#9CA3AF', fontSize: 18, lineHeight: 1 },
  badge: { fontSize: 12, fontWeight: 600 as const, padding: '3px 8px', borderRadius: 6 },
  role: { fontSize: 11, color: '#6B7280', background: '#F3F4F6', padding: '2px 6px', borderRadius: 4 },
  amount: { marginLeft: 'auto', fontSize: 16, color: '#111827' },
  price: { margin: 0, fontSize: 14, color: '#374151' },
  sub: { color: '#6B7280', fontSize: 13 },
  meta: { fontSize: 12, color: '#6B7280' },
  section: { display: 'flex', flexDirection: 'column' as const, gap: 8, borderTop: '1px solid #F3F4F6', paddingTop: 12 },
  sectionTitle: { margin: 0, fontSize: 13, fontWeight: 600 as const, color: '#374151' },
  input: { padding: '9px 11px', fontSize: 14, border: '1px solid #D1D5DB', borderRadius: 8 },
  primary: { padding: '11px', fontSize: 14, fontWeight: 600 as const, background: '#2563EB', color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer' },
  disabled: { padding: '11px', fontSize: 14, fontWeight: 600 as const, background: '#E5E7EB', color: '#9CA3AF', border: 'none', borderRadius: 8, cursor: 'not-allowed' },
  ghost: { padding: '9px', fontSize: 13, background: '#fff', color: '#6B7280', border: '1px solid #D1D5DB', borderRadius: 8, cursor: 'pointer' },
  okText: { margin: 0, fontSize: 13, color: '#065F46', lineHeight: 1.6 },
  warnText: { margin: 0, fontSize: 12, color: '#9A3412', lineHeight: 1.6 },
  dangerText: { margin: 0, fontSize: 13, color: '#991B1B', lineHeight: 1.6 },
  danger: { background: '#FEF2F2', border: '1px solid #FECACA', borderRadius: 8, padding: '10px 12px', display: 'flex', flexDirection: 'column' as const, gap: 6, color: '#991B1B' },
  checkbox: { display: 'flex', alignItems: 'center', gap: 6, fontSize: 13 },
  account: { background: '#F9FAFB', border: '1px solid #E5E7EB', borderRadius: 8, padding: '10px 12px' },
  accountLine: { margin: 0, fontSize: 14, color: '#111827', lineHeight: 1.7 },
  accountAmount: { margin: '6px 0 0', fontSize: 14, color: '#2563EB' },
  addr: { display: 'block', fontSize: 12, wordBreak: 'break-all' as const, background: '#F9FAFB', border: '1px solid #E5E7EB', borderRadius: 6, padding: '6px 8px' },
};
